name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.released }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release
        with:
          token: ${{ secrets.PAT }}
